version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: footballuz-api
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - footballuz

  admin:
    build:
      context: apps/admin
      dockerfile: Dockerfile
    container_name: footballuz-admin
    restart: always
    ports:
      - '3005:3000'
    env_file:
      - apps/admin/.env.local
    networks:
      - footballuz

  redis:
    image: redis:7-alpine
    container_name: footballuz-redis
    restart: always
    networks:
      - footballuz

networks:
  footballuz:
    driver: bridge
